name: MSVC Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  CONAN_REFERENCE: "mscl/0.1"
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  SINTEF_REMOTE: sintef
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-on-windows:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        build_type: [Debug, Release]
        compiler_version: [15, 16]

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan
          pip3 install conan_package_tools
      - name: Configure Conan
        run: conan remote add sintef https://api.bintray.com/conan/sintef-ocean/conan --insert 0
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -b missing . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef 'mscl*'
